train:
  model: "prajjwal1/bert-tiny"
  batch_size: 32
  epochs: 1
  eval_size: 0.3
  use_cuda: true
  train_csv: "/data/train.csv"
  output_dir: "/model"
  checkpoint_file: "checkpoint.txt"
client:
  host: "http://host.docker.internal:8899"