version: '3.8'
services:
  train:
    build: .
    command: ["python", "train.py"]
    volumes:
      - ./model:/model
      - ./data:/data
      - ./config.yaml:/app/config.yaml
    profiles:
      - norun
  train_cuda:
    build:
      context: .
      dockerfile: cuda.Dockerfile
    command: ["python", "train.py"]
    volumes:
      - ./model:/model
      - ./data:/data
      - ./config.yaml:/app/config.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    profiles:
      - norun
  server:
    build: .
    command: ["python", "server.py"]
    ports:
      - "8899:80"
    volumes:
      - ./model:/model
      - ./config.yaml:/app/config.yaml
    profiles:
      - norun
  client:
    build: .
    command: ["python", "client.py"]
    tty: true
    stdin_open: true
    volumes:
      - ./config.yaml:/app/config.yaml
    profiles:
      - norun