version: '3'
services:
  train:
    build: .
    command: ["python", "train.py"]
    volumes:
      - ./model:/model
      - ./data:/data
      - ./config.yaml:/app/config.yaml
    profiles:
      - norun
  server:
    build: .
    command: ["python", "server.py"]
    ports:
      - "8899:80"
    volumes:
      - ./model:/model
      - ./config.yaml:/app/config.yaml
    profiles:
      - norun
  client:
    build: .
    command: ["python", "client.py"]
    tty: true
    stdin_open: true
    volumes:
      - ./config.yaml:/app/config.yaml
    profiles:
      - norun